export default [
  {
    name: "Default",
    value: {
      intro:{
        title:["History","1821"],
        subtitle:["Timeline","1821-1826"],
        backgroundImage:"assets/background.jpg"
      },
      slide1:{
        backgroundImage:"assets/background1.jpg",
        centerImage:"assets/Diakos.jpg",
        year:"1821",
        text:["Lorem", "ipsum", "dolor", "sit", "amet", ",","consectetur", "adipiscing", "elit",".", "Aenean", "pellentesque", "dignissim", "tellus","."],
        backgroundText1:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fermentum aliquam odio, sit amet posuere augue accumsan non. Quisque eget ex nibh. Phasellus vehicula risus eleifend dui porta blandit. Vivamus a lacinia enim. Nulla et auctor metus, a tristique magna. Donec sollicitudin nisl ut nisi congue, vel convallis enim sollicitudin. Nullam quis ultrices diam. Sed vel convallis ante. Quisque rutrum rhoncus ligula quis dignissim. Quisque lacinia nisi eget nisl euismod placerat. Donec vel turpis consectetur, feugiat dui id, imperdiet orci. Aenean condimentum felis vel varius ultrices.

        Mauris venenatis nec elit vitae pretium. Quisque eu cursus nisi. Nulla consequat venenatis massa ac pretium. In cursus tellus a ligula eleifend, quis pellentesque quam ullamcorper. Aliquam eget neque consectetur, hendrerit massa sed, vehicula elit. Etiam vel purus eu velit egestas ultrices non sed enim. Curabitur accumsan mauris in risus dignissim blandit. Mauris elementum urna ligula, non placerat odio convallis sit amet. Fusce interdum ac justo in mollis. Donec et viverra odio, eu finibus urna. Donec pretium tellus in tincidunt rutrum. Nullam leo enim, condimentum id est lacinia, maximus molestie lectus. Cras tempor at orci vitae ultrices. Curabitur egestas elit sed nisl ornare auctor.

        Cras at neque ac ligula luctus posuere at vel odio. Nunc pharetra, urna non mattis lacinia, risus lorem blandit diam, sit amet accumsan dui lectus a dui. Phasellus sollicitudin vel justo quis finibus. Sed at pretium lorem, vel viverra mauris. Sed non convallis sapien. Fusce porttitor euismod eros, non iaculis justo suscipit sed. In sed venenatis eros. Nam id finibus lorem, id luctus nisl. Nunc maximus massa ex, in consequat nulla euismod sed. Pellentesque faucibus facilisis consequat.

        Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex. Ut sed dui non magna rutrum finibus ut ac orci. Nulla luctus, risus id auctor pretium, nulla erat ornare ex, sit amet tincidunt magna libero ac urna. Morbi lobortis condimentum tortor et commodo. Praesent a neque eros. Nunc pulvinar tortor turpis, vitae tincidunt dolor vestibulum non. Mauris sit amet erat sed leo tincidunt interdum vitae gravida purus. 
        Quisque accumsan ante ac quam pretium dignissim. Proin posuere velit sed risus hendrerit, vel tincidunt ex cursus.`,
        backgroundText2:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fermentum aliquam odio, sit amet posuere augue accumsan non. Quisque eget ex nibh. Phasellus vehicula risus eleifend dui porta blandit. Vivamus a lacinia enim. Nulla et auctor metus, a tristique magna. Donec sollicitudin nisl ut nisi congue, vel convallis enim sollicitudin. Nullam quis ultrices diam. Sed vel convallis ante. Quisque rutrum rhoncus ligula quis dignissim. Quisque lacinia nisi eget nisl euismod placerat. Donec vel turpis consectetur, feugiat dui id, imperdiet orci. Aenean condimentum felis vel varius ultrices.

        Mauris venenatis nec elit vitae pretium. Quisque eu cursus nisi. Nulla consequat venenatis massa ac pretium. In cursus tellus a ligula eleifend, quis pellentesque quam ullamcorper. Aliquam eget neque consectetur, hendrerit massa sed, vehicula elit. Etiam vel purus eu velit egestas ultrices non sed enim. Curabitur accumsan mauris in risus dignissim blandit. Mauris elementum urna ligula, non placerat odio convallis sit amet. Fusce interdum ac justo in mollis. Donec et viverra odio, eu finibus urna. Donec pretium tellus in tincidunt rutrum. Nullam leo enim, condimentum id est lacinia, maximus molestie lectus. Cras tempor at orci vitae ultrices. Curabitur egestas elit sed nisl ornare auctor.
        
        Cras at neque ac ligula luctus posuere at vel odio. Nunc pharetra, urna non mattis lacinia, risus lorem blandit diam, sit amet accumsan dui lectus a dui. Phasellus sollicitudin vel justo quis finibus. Sed at pretium lorem, vel viverra mauris. Sed non convallis sapien. Fusce porttitor euismod eros, non iaculis justo suscipit sed. In sed venenatis eros. Nam id finibus lorem, id luctus nisl. Nunc maximus massa ex, in consequat nulla euismod sed. Pellentesque faucibus facilisis consequat.
        
        Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex. Ut sed dui non magna rutrum finibus ut ac orci. Nulla luctus, risus id auctor pretium, nulla erat ornare ex, sit amet tincidunt magna libero ac urna. Morbi lobortis condimentum tortor et commodo. Praesent a neque eros. Nunc pulvinar tortor turpis, vitae tincidunt dolor vestibulum non. Mauris sit amet erat sed leo tincidunt interdum vitae gravida purus. 
        Quisque accumsan ante ac quam pretium dignissim. Proin posuere velit sed risus hendrerit, vel tincidunt ex cursus.`,
        textEffect:"Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex."
      },
      slide2:{
        backgroundImage:"assets/background2.jpg",
        centerImage:"assets/Nicolas.jpg",
        year:"1822",
        text:["Lorem", "ipsum", "dolor", "sit", "amet", ",","consectetur", "adipiscing", "elit",".", "Aenean", "pellentesque", "dignissim", "tellus","."],
        backgroundText1:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fermentum aliquam odio, sit amet posuere augue accumsan non. Quisque eget ex nibh. Phasellus vehicula risus eleifend dui porta blandit. Vivamus a lacinia enim. Nulla et auctor metus, a tristique magna. Donec sollicitudin nisl ut nisi congue, vel convallis enim sollicitudin. Nullam quis ultrices diam. Sed vel convallis ante. Quisque rutrum rhoncus ligula quis dignissim. Quisque lacinia nisi eget nisl euismod placerat. Donec vel turpis consectetur, feugiat dui id, imperdiet orci. Aenean condimentum felis vel varius ultrices.

        Mauris venenatis nec elit vitae pretium. Quisque eu cursus nisi. Nulla consequat venenatis massa ac pretium. In cursus tellus a ligula eleifend, quis pellentesque quam ullamcorper. Aliquam eget neque consectetur, hendrerit massa sed, vehicula elit. Etiam vel purus eu velit egestas ultrices non sed enim. Curabitur accumsan mauris in risus dignissim blandit. Mauris elementum urna ligula, non placerat odio convallis sit amet. Fusce interdum ac justo in mollis. Donec et viverra odio, eu finibus urna. Donec pretium tellus in tincidunt rutrum. Nullam leo enim, condimentum id est lacinia, maximus molestie lectus. Cras tempor at orci vitae ultrices. Curabitur egestas elit sed nisl ornare auctor.

        Cras at neque ac ligula luctus posuere at vel odio. Nunc pharetra, urna non mattis lacinia, risus lorem blandit diam, sit amet accumsan dui lectus a dui. Phasellus sollicitudin vel justo quis finibus. Sed at pretium lorem, vel viverra mauris. Sed non convallis sapien. Fusce porttitor euismod eros, non iaculis justo suscipit sed. In sed venenatis eros. Nam id finibus lorem, id luctus nisl. Nunc maximus massa ex, in consequat nulla euismod sed. Pellentesque faucibus facilisis consequat.

        Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex. Ut sed dui non magna rutrum finibus ut ac orci. Nulla luctus, risus id auctor pretium, nulla erat ornare ex, sit amet tincidunt magna libero ac urna. Morbi lobortis condimentum tortor et commodo. Praesent a neque eros. Nunc pulvinar tortor turpis, vitae tincidunt dolor vestibulum non. Mauris sit amet erat sed leo tincidunt interdum vitae gravida purus. 
        Quisque accumsan ante ac quam pretium dignissim. Proin posuere velit sed risus hendrerit, vel tincidunt ex cursus.`,
        backgroundText2:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fermentum aliquam odio, sit amet posuere augue accumsan non. Quisque eget ex nibh. Phasellus vehicula risus eleifend dui porta blandit. Vivamus a lacinia enim. Nulla et auctor metus, a tristique magna. Donec sollicitudin nisl ut nisi congue, vel convallis enim sollicitudin. Nullam quis ultrices diam. Sed vel convallis ante. Quisque rutrum rhoncus ligula quis dignissim. Quisque lacinia nisi eget nisl euismod placerat. Donec vel turpis consectetur, feugiat dui id, imperdiet orci. Aenean condimentum felis vel varius ultrices.

        Mauris venenatis nec elit vitae pretium. Quisque eu cursus nisi. Nulla consequat venenatis massa ac pretium. In cursus tellus a ligula eleifend, quis pellentesque quam ullamcorper. Aliquam eget neque consectetur, hendrerit massa sed, vehicula elit. Etiam vel purus eu velit egestas ultrices non sed enim. Curabitur accumsan mauris in risus dignissim blandit. Mauris elementum urna ligula, non placerat odio convallis sit amet. Fusce interdum ac justo in mollis. Donec et viverra odio, eu finibus urna. Donec pretium tellus in tincidunt rutrum. Nullam leo enim, condimentum id est lacinia, maximus molestie lectus. Cras tempor at orci vitae ultrices. Curabitur egestas elit sed nisl ornare auctor.
        
        Cras at neque ac ligula luctus posuere at vel odio. Nunc pharetra, urna non mattis lacinia, risus lorem blandit diam, sit amet accumsan dui lectus a dui. Phasellus sollicitudin vel justo quis finibus. Sed at pretium lorem, vel viverra mauris. Sed non convallis sapien. Fusce porttitor euismod eros, non iaculis justo suscipit sed. In sed venenatis eros. Nam id finibus lorem, id luctus nisl. Nunc maximus massa ex, in consequat nulla euismod sed. Pellentesque faucibus facilisis consequat.
        
        Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex. Ut sed dui non magna rutrum finibus ut ac orci. Nulla luctus, risus id auctor pretium, nulla erat ornare ex, sit amet tincidunt magna libero ac urna. Morbi lobortis condimentum tortor et commodo. Praesent a neque eros. Nunc pulvinar tortor turpis, vitae tincidunt dolor vestibulum non. Mauris sit amet erat sed leo tincidunt interdum vitae gravida purus. 
        Quisque accumsan ante ac quam pretium dignissim. Proin posuere velit sed risus hendrerit, vel tincidunt ex cursus.`,
        textEffect:"Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex."
      },
      slide3:{
        backgroundImage:"assets/background3.jpg",
        centerImage:"assets/background1.jpg",
        year:"1823",
        text:["Lorem", "ipsum", "dolor", "sit", "amet", ",","consectetur", "adipiscing", "elit",".", "Aenean", "pellentesque", "dignissim", "tellus","."],
        backgroundText1:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fermentum aliquam odio, sit amet posuere augue accumsan non. Quisque eget ex nibh. Phasellus vehicula risus eleifend dui porta blandit. Vivamus a lacinia enim. Nulla et auctor metus, a tristique magna. Donec sollicitudin nisl ut nisi congue, vel convallis enim sollicitudin. Nullam quis ultrices diam. Sed vel convallis ante. Quisque rutrum rhoncus ligula quis dignissim. Quisque lacinia nisi eget nisl euismod placerat. Donec vel turpis consectetur, feugiat dui id, imperdiet orci. Aenean condimentum felis vel varius ultrices.

        Mauris venenatis nec elit vitae pretium. Quisque eu cursus nisi. Nulla consequat venenatis massa ac pretium. In cursus tellus a ligula eleifend, quis pellentesque quam ullamcorper. Aliquam eget neque consectetur, hendrerit massa sed, vehicula elit. Etiam vel purus eu velit egestas ultrices non sed enim. Curabitur accumsan mauris in risus dignissim blandit. Mauris elementum urna ligula, non placerat odio convallis sit amet. Fusce interdum ac justo in mollis. Donec et viverra odio, eu finibus urna. Donec pretium tellus in tincidunt rutrum. Nullam leo enim, condimentum id est lacinia, maximus molestie lectus. Cras tempor at orci vitae ultrices. Curabitur egestas elit sed nisl ornare auctor.

        Cras at neque ac ligula luctus posuere at vel odio. Nunc pharetra, urna non mattis lacinia, risus lorem blandit diam, sit amet accumsan dui lectus a dui. Phasellus sollicitudin vel justo quis finibus. Sed at pretium lorem, vel viverra mauris. Sed non convallis sapien. Fusce porttitor euismod eros, non iaculis justo suscipit sed. In sed venenatis eros. Nam id finibus lorem, id luctus nisl. Nunc maximus massa ex, in consequat nulla euismod sed. Pellentesque faucibus facilisis consequat.

        Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex. Ut sed dui non magna rutrum finibus ut ac orci. Nulla luctus, risus id auctor pretium, nulla erat ornare ex, sit amet tincidunt magna libero ac urna. Morbi lobortis condimentum tortor et commodo. Praesent a neque eros. Nunc pulvinar tortor turpis, vitae tincidunt dolor vestibulum non. Mauris sit amet erat sed leo tincidunt interdum vitae gravida purus. 
        Quisque accumsan ante ac quam pretium dignissim. Proin posuere velit sed risus hendrerit, vel tincidunt ex cursus.`,
        backgroundText2:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fermentum aliquam odio, sit amet posuere augue accumsan non. Quisque eget ex nibh. Phasellus vehicula risus eleifend dui porta blandit. Vivamus a lacinia enim. Nulla et auctor metus, a tristique magna. Donec sollicitudin nisl ut nisi congue, vel convallis enim sollicitudin. Nullam quis ultrices diam. Sed vel convallis ante. Quisque rutrum rhoncus ligula quis dignissim. Quisque lacinia nisi eget nisl euismod placerat. Donec vel turpis consectetur, feugiat dui id, imperdiet orci. Aenean condimentum felis vel varius ultrices.

        Mauris venenatis nec elit vitae pretium. Quisque eu cursus nisi. Nulla consequat venenatis massa ac pretium. In cursus tellus a ligula eleifend, quis pellentesque quam ullamcorper. Aliquam eget neque consectetur, hendrerit massa sed, vehicula elit. Etiam vel purus eu velit egestas ultrices non sed enim. Curabitur accumsan mauris in risus dignissim blandit. Mauris elementum urna ligula, non placerat odio convallis sit amet. Fusce interdum ac justo in mollis. Donec et viverra odio, eu finibus urna. Donec pretium tellus in tincidunt rutrum. Nullam leo enim, condimentum id est lacinia, maximus molestie lectus. Cras tempor at orci vitae ultrices. Curabitur egestas elit sed nisl ornare auctor.
        
        Cras at neque ac ligula luctus posuere at vel odio. Nunc pharetra, urna non mattis lacinia, risus lorem blandit diam, sit amet accumsan dui lectus a dui. Phasellus sollicitudin vel justo quis finibus. Sed at pretium lorem, vel viverra mauris. Sed non convallis sapien. Fusce porttitor euismod eros, non iaculis justo suscipit sed. In sed venenatis eros. Nam id finibus lorem, id luctus nisl. Nunc maximus massa ex, in consequat nulla euismod sed. Pellentesque faucibus facilisis consequat.
        
        Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex. Ut sed dui non magna rutrum finibus ut ac orci. Nulla luctus, risus id auctor pretium, nulla erat ornare ex, sit amet tincidunt magna libero ac urna. Morbi lobortis condimentum tortor et commodo. Praesent a neque eros. Nunc pulvinar tortor turpis, vitae tincidunt dolor vestibulum non. Mauris sit amet erat sed leo tincidunt interdum vitae gravida purus. 
        Quisque accumsan ante ac quam pretium dignissim. Proin posuere velit sed risus hendrerit, vel tincidunt ex cursus.`,
        textEffect:"Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex."
      },
      slide4:{
        backgroundImage:"assets/background4.jpg",
        centerImage:"assets/background6.jpg",
        year:"1824",
        text:["Lorem", "ipsum", "dolor", "sit", "amet", ",","consectetur", "adipiscing", "elit",".", "Aenean", "pellentesque", "dignissim", "tellus","."],
        backgroundText1:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fermentum aliquam odio, sit amet posuere augue accumsan non. Quisque eget ex nibh. Phasellus vehicula risus eleifend dui porta blandit. Vivamus a lacinia enim. Nulla et auctor metus, a tristique magna. Donec sollicitudin nisl ut nisi congue, vel convallis enim sollicitudin. Nullam quis ultrices diam. Sed vel convallis ante. Quisque rutrum rhoncus ligula quis dignissim. Quisque lacinia nisi eget nisl euismod placerat. Donec vel turpis consectetur, feugiat dui id, imperdiet orci. Aenean condimentum felis vel varius ultrices.

        Mauris venenatis nec elit vitae pretium. Quisque eu cursus nisi. Nulla consequat venenatis massa ac pretium. In cursus tellus a ligula eleifend, quis pellentesque quam ullamcorper. Aliquam eget neque consectetur, hendrerit massa sed, vehicula elit. Etiam vel purus eu velit egestas ultrices non sed enim. Curabitur accumsan mauris in risus dignissim blandit. Mauris elementum urna ligula, non placerat odio convallis sit amet. Fusce interdum ac justo in mollis. Donec et viverra odio, eu finibus urna. Donec pretium tellus in tincidunt rutrum. Nullam leo enim, condimentum id est lacinia, maximus molestie lectus. Cras tempor at orci vitae ultrices. Curabitur egestas elit sed nisl ornare auctor.

        Cras at neque ac ligula luctus posuere at vel odio. Nunc pharetra, urna non mattis lacinia, risus lorem blandit diam, sit amet accumsan dui lectus a dui. Phasellus sollicitudin vel justo quis finibus. Sed at pretium lorem, vel viverra mauris. Sed non convallis sapien. Fusce porttitor euismod eros, non iaculis justo suscipit sed. In sed venenatis eros. Nam id finibus lorem, id luctus nisl. Nunc maximus massa ex, in consequat nulla euismod sed. Pellentesque faucibus facilisis consequat.

        Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex. Ut sed dui non magna rutrum finibus ut ac orci. Nulla luctus, risus id auctor pretium, nulla erat ornare ex, sit amet tincidunt magna libero ac urna. Morbi lobortis condimentum tortor et commodo. Praesent a neque eros. Nunc pulvinar tortor turpis, vitae tincidunt dolor vestibulum non. Mauris sit amet erat sed leo tincidunt interdum vitae gravida purus. 
        Quisque accumsan ante ac quam pretium dignissim. Proin posuere velit sed risus hendrerit, vel tincidunt ex cursus.`,
        backgroundText2:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fermentum aliquam odio, sit amet posuere augue accumsan non. Quisque eget ex nibh. Phasellus vehicula risus eleifend dui porta blandit. Vivamus a lacinia enim. Nulla et auctor metus, a tristique magna. Donec sollicitudin nisl ut nisi congue, vel convallis enim sollicitudin. Nullam quis ultrices diam. Sed vel convallis ante. Quisque rutrum rhoncus ligula quis dignissim. Quisque lacinia nisi eget nisl euismod placerat. Donec vel turpis consectetur, feugiat dui id, imperdiet orci. Aenean condimentum felis vel varius ultrices.

        Mauris venenatis nec elit vitae pretium. Quisque eu cursus nisi. Nulla consequat venenatis massa ac pretium. In cursus tellus a ligula eleifend, quis pellentesque quam ullamcorper. Aliquam eget neque consectetur, hendrerit massa sed, vehicula elit. Etiam vel purus eu velit egestas ultrices non sed enim. Curabitur accumsan mauris in risus dignissim blandit. Mauris elementum urna ligula, non placerat odio convallis sit amet. Fusce interdum ac justo in mollis. Donec et viverra odio, eu finibus urna. Donec pretium tellus in tincidunt rutrum. Nullam leo enim, condimentum id est lacinia, maximus molestie lectus. Cras tempor at orci vitae ultrices. Curabitur egestas elit sed nisl ornare auctor.
        
        Cras at neque ac ligula luctus posuere at vel odio. Nunc pharetra, urna non mattis lacinia, risus lorem blandit diam, sit amet accumsan dui lectus a dui. Phasellus sollicitudin vel justo quis finibus. Sed at pretium lorem, vel viverra mauris. Sed non convallis sapien. Fusce porttitor euismod eros, non iaculis justo suscipit sed. In sed venenatis eros. Nam id finibus lorem, id luctus nisl. Nunc maximus massa ex, in consequat nulla euismod sed. Pellentesque faucibus facilisis consequat.
        
        Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex. Ut sed dui non magna rutrum finibus ut ac orci. Nulla luctus, risus id auctor pretium, nulla erat ornare ex, sit amet tincidunt magna libero ac urna. Morbi lobortis condimentum tortor et commodo. Praesent a neque eros. Nunc pulvinar tortor turpis, vitae tincidunt dolor vestibulum non. Mauris sit amet erat sed leo tincidunt interdum vitae gravida purus. 
        Quisque accumsan ante ac quam pretium dignissim. Proin posuere velit sed risus hendrerit, vel tincidunt ex cursus.`,
        textEffect:"Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex."
      },
      slide5:{
        backgroundImage:"assets/background5.jpg",
        centerImage:"assets/Manto.jpg",
        year:"1825",
        text:["Lorem", "ipsum", "dolor", "sit", "amet", ",","consectetur", "adipiscing", "elit",".", "Aenean", "pellentesque", "dignissim", "tellus","."],
        backgroundText1:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fermentum aliquam odio, sit amet posuere augue accumsan non. Quisque eget ex nibh. Phasellus vehicula risus eleifend dui porta blandit. Vivamus a lacinia enim. Nulla et auctor metus, a tristique magna. Donec sollicitudin nisl ut nisi congue, vel convallis enim sollicitudin. Nullam quis ultrices diam. Sed vel convallis ante. Quisque rutrum rhoncus ligula quis dignissim. Quisque lacinia nisi eget nisl euismod placerat. Donec vel turpis consectetur, feugiat dui id, imperdiet orci. Aenean condimentum felis vel varius ultrices.

        Mauris venenatis nec elit vitae pretium. Quisque eu cursus nisi. Nulla consequat venenatis massa ac pretium. In cursus tellus a ligula eleifend, quis pellentesque quam ullamcorper. Aliquam eget neque consectetur, hendrerit massa sed, vehicula elit. Etiam vel purus eu velit egestas ultrices non sed enim. Curabitur accumsan mauris in risus dignissim blandit. Mauris elementum urna ligula, non placerat odio convallis sit amet. Fusce interdum ac justo in mollis. Donec et viverra odio, eu finibus urna. Donec pretium tellus in tincidunt rutrum. Nullam leo enim, condimentum id est lacinia, maximus molestie lectus. Cras tempor at orci vitae ultrices. Curabitur egestas elit sed nisl ornare auctor.

        Cras at neque ac ligula luctus posuere at vel odio. Nunc pharetra, urna non mattis lacinia, risus lorem blandit diam, sit amet accumsan dui lectus a dui. Phasellus sollicitudin vel justo quis finibus. Sed at pretium lorem, vel viverra mauris. Sed non convallis sapien. Fusce porttitor euismod eros, non iaculis justo suscipit sed. In sed venenatis eros. Nam id finibus lorem, id luctus nisl. Nunc maximus massa ex, in consequat nulla euismod sed. Pellentesque faucibus facilisis consequat.

        Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex. Ut sed dui non magna rutrum finibus ut ac orci. Nulla luctus, risus id auctor pretium, nulla erat ornare ex, sit amet tincidunt magna libero ac urna. Morbi lobortis condimentum tortor et commodo. Praesent a neque eros. Nunc pulvinar tortor turpis, vitae tincidunt dolor vestibulum non. Mauris sit amet erat sed leo tincidunt interdum vitae gravida purus. 
        Quisque accumsan ante ac quam pretium dignissim. Proin posuere velit sed risus hendrerit, vel tincidunt ex cursus.`,
        backgroundText2:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fermentum aliquam odio, sit amet posuere augue accumsan non. Quisque eget ex nibh. Phasellus vehicula risus eleifend dui porta blandit. Vivamus a lacinia enim. Nulla et auctor metus, a tristique magna. Donec sollicitudin nisl ut nisi congue, vel convallis enim sollicitudin. Nullam quis ultrices diam. Sed vel convallis ante. Quisque rutrum rhoncus ligula quis dignissim. Quisque lacinia nisi eget nisl euismod placerat. Donec vel turpis consectetur, feugiat dui id, imperdiet orci. Aenean condimentum felis vel varius ultrices.

        Mauris venenatis nec elit vitae pretium. Quisque eu cursus nisi. Nulla consequat venenatis massa ac pretium. In cursus tellus a ligula eleifend, quis pellentesque quam ullamcorper. Aliquam eget neque consectetur, hendrerit massa sed, vehicula elit. Etiam vel purus eu velit egestas ultrices non sed enim. Curabitur accumsan mauris in risus dignissim blandit. Mauris elementum urna ligula, non placerat odio convallis sit amet. Fusce interdum ac justo in mollis. Donec et viverra odio, eu finibus urna. Donec pretium tellus in tincidunt rutrum. Nullam leo enim, condimentum id est lacinia, maximus molestie lectus. Cras tempor at orci vitae ultrices. Curabitur egestas elit sed nisl ornare auctor.
        
        Cras at neque ac ligula luctus posuere at vel odio. Nunc pharetra, urna non mattis lacinia, risus lorem blandit diam, sit amet accumsan dui lectus a dui. Phasellus sollicitudin vel justo quis finibus. Sed at pretium lorem, vel viverra mauris. Sed non convallis sapien. Fusce porttitor euismod eros, non iaculis justo suscipit sed. In sed venenatis eros. Nam id finibus lorem, id luctus nisl. Nunc maximus massa ex, in consequat nulla euismod sed. Pellentesque faucibus facilisis consequat.
        
        Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex. Ut sed dui non magna rutrum finibus ut ac orci. Nulla luctus, risus id auctor pretium, nulla erat ornare ex, sit amet tincidunt magna libero ac urna. Morbi lobortis condimentum tortor et commodo. Praesent a neque eros. Nunc pulvinar tortor turpis, vitae tincidunt dolor vestibulum non. Mauris sit amet erat sed leo tincidunt interdum vitae gravida purus. 
        Quisque accumsan ante ac quam pretium dignissim. Proin posuere velit sed risus hendrerit, vel tincidunt ex cursus.`,
        textEffect:"Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex."
      },
      slide6:{
        backgroundImage:"assets/background6.jpg",
        centerImage:"assets/background2.jpg",
        year:"1826",
        text:["Lorem", "ipsum", "dolor", "sit", "amet", ",","consectetur", "adipiscing", "elit",".", "Aenean", "pellentesque", "dignissim", "tellus","."],
        backgroundText1:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fermentum aliquam odio, sit amet posuere augue accumsan non. Quisque eget ex nibh. Phasellus vehicula risus eleifend dui porta blandit. Vivamus a lacinia enim. Nulla et auctor metus, a tristique magna. Donec sollicitudin nisl ut nisi congue, vel convallis enim sollicitudin. Nullam quis ultrices diam. Sed vel convallis ante. Quisque rutrum rhoncus ligula quis dignissim. Quisque lacinia nisi eget nisl euismod placerat. Donec vel turpis consectetur, feugiat dui id, imperdiet orci. Aenean condimentum felis vel varius ultrices.

        Mauris venenatis nec elit vitae pretium. Quisque eu cursus nisi. Nulla consequat venenatis massa ac pretium. In cursus tellus a ligula eleifend, quis pellentesque quam ullamcorper. Aliquam eget neque consectetur, hendrerit massa sed, vehicula elit. Etiam vel purus eu velit egestas ultrices non sed enim. Curabitur accumsan mauris in risus dignissim blandit. Mauris elementum urna ligula, non placerat odio convallis sit amet. Fusce interdum ac justo in mollis. Donec et viverra odio, eu finibus urna. Donec pretium tellus in tincidunt rutrum. Nullam leo enim, condimentum id est lacinia, maximus molestie lectus. Cras tempor at orci vitae ultrices. Curabitur egestas elit sed nisl ornare auctor.

        Cras at neque ac ligula luctus posuere at vel odio. Nunc pharetra, urna non mattis lacinia, risus lorem blandit diam, sit amet accumsan dui lectus a dui. Phasellus sollicitudin vel justo quis finibus. Sed at pretium lorem, vel viverra mauris. Sed non convallis sapien. Fusce porttitor euismod eros, non iaculis justo suscipit sed. In sed venenatis eros. Nam id finibus lorem, id luctus nisl. Nunc maximus massa ex, in consequat nulla euismod sed. Pellentesque faucibus facilisis consequat.

        Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex. Ut sed dui non magna rutrum finibus ut ac orci. Nulla luctus, risus id auctor pretium, nulla erat ornare ex, sit amet tincidunt magna libero ac urna. Morbi lobortis condimentum tortor et commodo. Praesent a neque eros. Nunc pulvinar tortor turpis, vitae tincidunt dolor vestibulum non. Mauris sit amet erat sed leo tincidunt interdum vitae gravida purus. 
        Quisque accumsan ante ac quam pretium dignissim. Proin posuere velit sed risus hendrerit, vel tincidunt ex cursus.`,
        backgroundText2:`Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur fermentum aliquam odio, sit amet posuere augue accumsan non. Quisque eget ex nibh. Phasellus vehicula risus eleifend dui porta blandit. Vivamus a lacinia enim. Nulla et auctor metus, a tristique magna. Donec sollicitudin nisl ut nisi congue, vel convallis enim sollicitudin. Nullam quis ultrices diam. Sed vel convallis ante. Quisque rutrum rhoncus ligula quis dignissim. Quisque lacinia nisi eget nisl euismod placerat. Donec vel turpis consectetur, feugiat dui id, imperdiet orci. Aenean condimentum felis vel varius ultrices.

        Mauris venenatis nec elit vitae pretium. Quisque eu cursus nisi. Nulla consequat venenatis massa ac pretium. In cursus tellus a ligula eleifend, quis pellentesque quam ullamcorper. Aliquam eget neque consectetur, hendrerit massa sed, vehicula elit. Etiam vel purus eu velit egestas ultrices non sed enim. Curabitur accumsan mauris in risus dignissim blandit. Mauris elementum urna ligula, non placerat odio convallis sit amet. Fusce interdum ac justo in mollis. Donec et viverra odio, eu finibus urna. Donec pretium tellus in tincidunt rutrum. Nullam leo enim, condimentum id est lacinia, maximus molestie lectus. Cras tempor at orci vitae ultrices. Curabitur egestas elit sed nisl ornare auctor.
        
        Cras at neque ac ligula luctus posuere at vel odio. Nunc pharetra, urna non mattis lacinia, risus lorem blandit diam, sit amet accumsan dui lectus a dui. Phasellus sollicitudin vel justo quis finibus. Sed at pretium lorem, vel viverra mauris. Sed non convallis sapien. Fusce porttitor euismod eros, non iaculis justo suscipit sed. In sed venenatis eros. Nam id finibus lorem, id luctus nisl. Nunc maximus massa ex, in consequat nulla euismod sed. Pellentesque faucibus facilisis consequat.
        
        Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex. Ut sed dui non magna rutrum finibus ut ac orci. Nulla luctus, risus id auctor pretium, nulla erat ornare ex, sit amet tincidunt magna libero ac urna. Morbi lobortis condimentum tortor et commodo. Praesent a neque eros. Nunc pulvinar tortor turpis, vitae tincidunt dolor vestibulum non. Mauris sit amet erat sed leo tincidunt interdum vitae gravida purus. 
        Quisque accumsan ante ac quam pretium dignissim. Proin posuere velit sed risus hendrerit, vel tincidunt ex cursus.`,
        textEffect:"Nam hendrerit diam ante, hendrerit pretium risus pharetra a. Nunc vulputate purus ut accumsan auctor. Donec scelerisque mi id justo lacinia, sit amet blandit nisl semper. Maecenas auctor risus maximus dui porta, ac pharetra nisl ultricies. Proin varius massa orci, non egestas nibh mattis quis. Etiam ultrices ullamcorper nunc, vitae tempus erat ultricies sit amet. Aliquam erat volutpat. Curabitur a dui id massa bibendum condimentum nec eget ex."
      },
      outro:{
        title:["History","1821"],
        subtitle:["by","Maria","Ioannou"],
        backgroundImage:"assets/background7.jpg"
      },
    },
  },

];
